version: '3'
services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - MQTT_BROKER_URL=mqtt
      - MQTT_BROKER_PORT=1883
      - DBConnection="mongodb://mongo:27017"
      - DB_USER=reak
      - DB_PASSWORD=reak
      - DB_NAME=calendarTest2
      - SESSION_KEY=reakgo
      - SESSION_NAME=reakgo
      - WEB_PORT=4000
      - APPNAME=REAK
      - APPURL=http://localhost:4000/
      - FROM_USER=apikey
      - FROM_EMAIL=user@reak.in
      - PASSWORD=123
      - SMTP_HOST=smtp.sendgrid.net
      - SMTP_PORT=587
      - EMAIL_TOKEN_EXPIRE=86400

    depends_on:
      - mqtt
      - mongo
    #restart: always
  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
  mongo:
    image: mongo:latest
    volumes:
      - ./mongo-data:/data/db